name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  

    env:
      Solution_Name: Backend.sln
      Test_Project_Path: Backend

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Copy database from DbTemplate to Backend
    - name: Copy database to project
      run: copy DbTemplate\\_db.sqlite3 Backend

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --logger "console;verbosity=detailed"

    # Start backend non-blocking
    - name: Start the backend
      shell: bash
      run: cd Backend && nohup dotnet run &

    # Run the endpoint tests
    # (note: The reason we don't have to install Newman
    #  is that it is already installed in the 
    #  GitHub Actions Windows Server runner image)
    - name: Run the endpoint tests
      shell: bash
      run: cd endpoint-tests && npm test

    # Run the UI tests
    - name: Run the UI tests
      shell: bash
      run: cd ui-tests && npm install && npm run test-ui-cli